Repository modern-agile-team/ModernWorld-back, pull requests merged in 2024-07, with the labels that each got.

#58 방명록에 대한 댓글 구현입니다.
  src/comments/comments.controller.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/dtos/comment-dtos/create-comment.dto.ts
  src/comments/dtos/comment-dtos/get-comment.dto.ts
  src/comments/dtos/comment-dtos/update-comment.dto.ts
  src/comments/dtos/replies-dtos/create-reply.dto.ts
  src/comments/dtos/replies-dtos/get-reply.dto.ts
  src/comments/dtos/replies-dtos/update-reply.dto.ts
  src/comments/swagger-decorators/comment-swagger/create-comment-decorator.ts
  src/comments/swagger-decorators/comment-swagger/delete-comments-decorator.ts
  src/comments/swagger-decorators/comment-swagger/find-comments-decorator.ts
  src/comments/swagger-decorators/comment-swagger/update-comment-decorator.ts
  src/comments/swagger-decorators/reply-swagger/create-reply-decorater.ts
  src/comments/swagger-decorators/reply-swagger/delete-reply-decorate.ts
  src/comments/swagger-decorators/reply-swagger/find-reply-decorate.ts
  src/comments/swagger-decorators/reply-swagger/update-reply-decorate.ts
Labels: feature

#61 알람 테이블 관련 로직 추가 (Redis로 구현 X)
  prisma/migrations/20240701050005_add_alarm/migration.sql
  prisma/schema.prisma
  src/alarms/alarms.controller.ts
  src/alarms/alarms.module.ts
  src/alarms/alarms.repository.ts
  src/alarms/alarms.service.ts
  src/app.module.ts
  src/common/dtos/pagination-response.dto.ts
  src/common/dtos/pagination.dto.ts
  src/common/enum/order-by.enum.ts
Labels: db, feature

#60 redis를 이용해 서비스 토큰 저장 로직입니다.
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.decorator.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/jwt.guard.ts
  src/auth/jwt.strategy.ts
  src/auth/redis.module.ts
  src/auth/redis.service.ts
  src/auth/token.repository.ts
  src/auth/token.service.ts
Labels: feature, modify

#64 swagger에서 헤더로 토큰 전달 가능하게 기능 추가
  src/auth/auth.controller.ts
  src/auth/jwt.guard.ts
  src/main.ts
Labels: bugfix, doc, modify

#73 Bugfix/#72 cookieInterceptor 추가
  src/auth/auth.controller.ts
  src/auth/interceptors/cookie.interceptor.ts
Labels: bugfix, modify, refactor

#74 Feature/#44/achievement
  prisma/schema.prisma
  src/comments/comments.controller.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/dtos/comment-dtos/comment-content.dto.ts
  src/comments/dtos/comment-dtos/comments-pagination.dto.ts
  src/comments/dtos/comment-dtos/create-comment.dto.ts
  src/comments/dtos/comment-dtos/get-comment.dto.ts
  src/comments/dtos/comment-dtos/update-comment.dto.ts
  src/comments/dtos/replies-dtos/create-reply.dto.ts
  src/comments/dtos/replies-dtos/get-reply.dto.ts
  src/comments/dtos/replies-dtos/update-reply.dto.ts
  src/comments/swagger-decorators/comment-swagger/create-comment-decorator.ts
  src/comments/swagger-decorators/comment-swagger/create-one-comment.decorator.ts
  src/comments/swagger-decorators/comment-swagger/delete-comments-decorator.ts
  src/comments/swagger-decorators/comment-swagger/delete-one-comment.decorator.ts
  src/comments/swagger-decorators/comment-swagger/find-comments-decorator.ts
  src/comments/swagger-decorators/comment-swagger/get-comments.decorator.ts
  src/comments/swagger-decorators/comment-swagger/update-comment-decorator.ts
  src/comments/swagger-decorators/comment-swagger/update-comment.decorator.ts
  src/comments/swagger-decorators/reply-swagger/create-one-reply.decorator.ts
  src/comments/swagger-decorators/reply-swagger/create-reply-decorater.ts
  src/comments/swagger-decorators/reply-swagger/delete-one-reply.decorator.ts
  src/comments/swagger-decorators/reply-swagger/delete-reply-decorate.ts
  src/comments/swagger-decorators/reply-swagger/find-reply-decorate.ts
  src/comments/swagger-decorators/reply-swagger/get-replies.decorator.ts
  src/comments/swagger-decorators/reply-swagger/update-one-reply.decorator.ts
  src/comments/swagger-decorators/reply-swagger/update-reply-decorate.ts
  src/common/common.service.ts
  src/inventory/inventory.module.ts
  src/inventory/inventory.service.ts
  src/likes/likes-swagger/find-one-like.decorator.ts
  src/likes/likes.controller.ts
  src/likes/likes.module.ts
  src/likes/likes.repository.ts
  src/likes/likes.service.ts
  src/presents/presents.module.ts
  src/presents/presents.service.ts
Labels: feature

#78 Modify/#76/login
  src/auth/interceptors/cookie.interceptor.ts
  src/auth/services/auth.service.ts
  src/auth/swagger-decorators/kakao-login-decorator.ts
  src/auth/swagger-decorators/naver-login-decorator.ts
Labels: modify, refactor

#80 Feature/#44/achievement
  src/comments/comments.module.ts
  src/comments/comments.service.ts
  src/common/common.module.ts
  src/common/common.service.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: feature

#70 Feature/#59/neighbor
  prisma/schema.prisma
  src/app.module.ts
  src/neighbors/dtos/neighbors-pagination.dto.ts
  src/neighbors/dtos/update-neighbor.dto.ts
  src/neighbors/neighbors.controller.ts
  src/neighbors/neighbors.module.ts
  src/neighbors/neighbors.repository.ts
  src/neighbors/neighbors.service.ts
  src/neighbors/swagger-decorators/create-one-neighbors.decorator.ts
  src/neighbors/swagger-decorators/delete-one-neighbor.decorator.ts
  src/neighbors/swagger-decorators/get-neighbors.decorator.ts
  src/neighbors/swagger-decorators/update-one-neighbor.decorator.ts
Labels: feature

#86 deploy/#82: docker-compose, nginx.conf 파일 추가 및 생성
  .dockerignore
  docker-compose.yml
  nginx.conf
Labels: deploy, feature, setting

#88 Refactor/#87/user
  docker-compose.yml
  nginx.conf
  package-lock.json
  package.json
  prisma/migrations/20240724114410_delete_refresh_token_and_make_user_no_unique/migration.sql
  prisma/schema.prisma
  src/presents/dtos/get-user-one-present-response.dto.ts
  src/presents/dtos/present.dto.ts
  src/users/dtos/get-users-by-animal.dto.ts
  src/users/enum/orderByFeild.enum.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: refactor

#90 deploy/#89: CICD 로직 main/dev 별로 수정
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/git-action-CD.yml
  .github/workflows/git-action.yml
  .github/workflows/main-CD.yml
Labels: deploy

#92 Feature/#81/test sse
  src/common/common.service.ts
  src/sse/sse.controller.ts
  src/sse/sse.service.ts
Labels: feature

#95 Feature/#94/comment alarm
  prisma/migrations/20240726025614_alarm_delete_url_and_create_title/migration.sql
  prisma/schema.prisma
  src/alarms/alarms.repository.ts
  src/comments/comments.module.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/common/common.service.ts
  src/sse/sse.controller.ts
  src/sse/sse.service.ts
Labels: feature

#91 Feature/#69/logout
  src/auth/auth.controller.ts
  src/auth/jwt/jwt.guard.ts
  src/auth/jwt/jwt.strategy.ts
  src/auth/repositories/token.repository.ts
  src/auth/services/auth.service.ts
  src/auth/services/token.service.ts
  src/auth/swagger-decorators/kakao-login-decorator.ts
  src/auth/swagger-decorators/kakao-logout-decorator.ts
  src/auth/swagger-decorators/naver-login-decorator.ts
  src/auth/swagger-decorators/naver-logout-decorator.ts
  src/likes/likes.service.ts
  src/neighbors/neighbors.service.ts
  src/posts/posts.service.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: feature

#97 Feature/#96/post alarm
  src/alarms/alarms.repository.ts
  src/inventory/inventory.service.ts
  src/posts/posts-swagger/create-one-post.decorator.ts
  src/posts/posts.module.ts
  src/posts/posts.repositroy.ts
  src/posts/posts.service.ts
  src/prisma/prisma.type.ts
Labels: feature

#99 modify user attendance API
  src/users/dtos/update-user-attendance.dto.ts
  src/users/users-swagger/get-user-attendance.decorator.ts
  src/users/users-swagger/update-user-attendance.decorator.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: feature

#102 Feature/#101/present alarm
  src/legends/legends.repository.ts
  src/presents/presents.module.ts
  src/presents/presents.repository.ts
  src/presents/presents.service.ts
  src/users/users.repository.ts
Labels: feature

#104 Feature/#69/logout
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/jwt/jwt.guard.ts
  src/auth/jwt/jwt.strategy.ts
  src/auth/repositories/token.repository.ts
  src/auth/services/auth.service.ts
  src/auth/services/token.service.ts
  src/auth/swagger-decorators/kakao-unlink-decorator.ts
  src/auth/swagger-decorators/naver-unlink-decorator.ts
  src/users/users.repository.ts
Labels: feature, modify

#105 Feature/#103/neighbor alarm
  src/app.module.ts
  src/likes/likes.service.ts
  src/neighbors/dtos/neighbors-pagination.dto.ts
  src/neighbors/dtos/update-neighbor.dto.ts
  src/neighbors/neighbors.controller.ts
  src/neighbors/neighbors.module.ts
  src/neighbors/neighbors.repository.ts
  src/neighbors/neighbors.service.ts
  src/neighbors/swagger-decorators/create-one-neighbors.decorator.ts
  src/neighbors/swagger-decorators/delete-one-neighbor.decorator.ts
  src/neighbors/swagger-decorators/get-neighbors.decorator.ts
  src/neighbors/swagger-decorators/update-one-neighbor.decorator.ts
Labels: feature
