Repository modern-agile-team/ModernWorld-back, pull requests merged in 2024-05, with the labels that each got.

#25 feature/#23: add seeding file 시딩파일 만들었어요
  prisma/seed.ts
  prisma/seeding/achievement.ts
  prisma/seeding/character.ts
  prisma/seeding/chrarcterLocker.ts
  prisma/seeding/comment.ts
  prisma/seeding/inventory.ts
  prisma/seeding/item.ts
  prisma/seeding/like.ts
  prisma/seeding/neighbor.ts
  prisma/seeding/post.ts
  prisma/seeding/present.ts
  prisma/seeding/reply.ts
  prisma/seeding/user.ts
  prisma/seeding/userAchievement.ts
Labels: db, feature

#27 Feature/#24/character
  src/app.module.ts
  src/characters/characters.controller.ts
  src/characters/characters.module.ts
  src/characters/characters.repository.ts
  src/characters/characters.service.ts
  src/characters/charactersLocker.repository.ts
Labels: feature

#28 Feature/#15/item
  src/app.module.ts
  src/inventory/inventory.repository.ts
  src/items/items.controller.ts
  src/items/items.module.ts
  src/items/items.repository.ts
  src/items/items.service.ts
Labels: feature

#29 Feature/#21/present
  src/app.module.ts
  src/presents/enum/present-senderReceiverNo-enum.ts
  src/presents/enum/present-status-enum.ts
  src/presents/presents.controller.ts
  src/presents/presents.module.ts
  src/presents/presents.repository.ts
  src/presents/presents.service.ts
Labels: feature

#34 Refactor/#30/object
  src/app.module.ts
  src/characterLocker/characterLocker.controller.ts
  src/characterLocker/characterLocker.module.ts
  src/characterLocker/characterLocker.repository.ts
  src/characterLocker/characterLocker.service.ts
  src/characters/characters.controller.ts
  src/characters/characters.module.ts
  src/characters/characters.repository.ts
  src/characters/characters.service.ts
  src/characters/charactersLocker.repository.ts
  src/characters/dtos/get-characters.dto.ts
  src/common/enum/animal.enum.ts
  src/inventory/dtos/get-user-items.dto.ts
  src/inventory/dtos/update-user-item-status.dto.ts
  src/inventory/inventory.controller.ts
  src/inventory/inventory.module.ts
  src/inventory/inventory.repository.ts
  src/inventory/inventory.service.ts
  src/items/dtos/get-user-all-items.dto.ts
  src/items/items.controller.ts
  src/items/items.module.ts
  src/items/items.repository.ts
  src/items/items.service.ts
  src/main.ts
  src/presents/dtos/present-accept-reject.dto.ts
  src/presents/enum/present-senderReceiverNo.enum.ts
  src/presents/enum/present-status.enum.ts
  src/presents/presents.controller.ts
  src/presents/presents.module.ts
  src/presents/presents.repository.ts
  src/presents/presents.service.ts
  src/prisma/prisma.service.spec.ts
  src/users/dtos/get-users-by-animal.dto.ts
  src/users/dtos/update-user-description.dto.ts
  src/users/dtos/update-user-nickname.dto.ts
  src/users/dtos/update-user.dto.ts
  src/users/enum/domain.enum.ts
  src/users/enum/orderByFeild.enum.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: feature, refactor

#37 Feature/#22/comment 방명록 API입니다.
  src/app.module.ts
  src/comment/comment.controller.ts
  src/comment/comment.module.ts
  src/comment/comment.repository.ts
  src/comment/comment.service.ts
  src/comment/dto/create-comment.dto.ts
  src/comment/dto/get-comment.dto.ts
  src/comment/dto/update-comment.dto.ts
Labels: feature

#39 유저 출석부 초기화 스케줄러 관련 PR
  package-lock.json
  package.json
  src/app.module.ts
  src/tasks/tasks.module.ts
  src/tasks/tasks.service.ts
  src/users/users.repository.ts
Labels: feature

#32 Feature/#11/auth : 네이버, 카카오 로그인 서비스 토큰 발급
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.decorator.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/jwt.dto.ts
  src/auth/jwt.guard.ts
  src/auth/jwt.strategy.ts
  src/auth/token.repository.ts
  src/auth/token.service.ts
  src/users/users.repository.ts
Labels: feature

#46 User 테이블에서 like 제거 및 seed 파일 추가
  prisma/migrations/20240530112156_delete_user_like/migration.sql
  prisma/migrations/20240531013107_comment_count/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  prisma/seeding/legend.ts
  src/users/users.repository.ts
Labels: bugfix
