Repository modern-agile-team/ModernWorld-back, pull requests merged in 2024-08, with the labels that each got.

#109 Refactor/#87/user
  src/neighbors/neighbors.repository.ts
  src/neighbors/neighbors.service.ts
  src/neighbors/swagger-decorators/get-neighbors.decorator.ts
  src/users/users-swagger/get-user-name-point-achievement.decorator.ts
  src/users/users-swagger/get-users.decorator.ts
Labels: feature

#110 feature/#11: 구글 로그인 구현
  src/auth/auth.controller.ts
  src/auth/services/auth.service.ts
  src/auth/swagger-decorators/google-login-decorator.ts
Labels: feature

#113 Feature/#107/game
  prisma/migrations/20240801114946_add_user_chance/migration.sql
  prisma/migrations/20240802014427_add_rsp_game/migration.sql
  prisma/migrations/20240802015513_add_legend_rsp_win_count/migration.sql
  prisma/schema.prisma
  prisma/seeding/achievement.ts
  src/app.module.ts
  src/games/constants/reward-point.constant.ts
  src/games/games.controller.ts
  src/games/games.module.ts
  src/games/rock-scissors-paper/dtos/rock-scissors-paper.dto.ts
  src/games/rock-scissors-paper/rock-scissors-paper.repository.ts
  src/games/rock-scissors-paper/rock-scissors-paper.service.ts
  src/games/rock-scissors-paper/type/rock-scissors-paper.type.ts
  src/games/swagger-decorators/create-RSP-record.decorator.ts
  src/games/swagger-decorators/get-RSP-records.decorator.ts
  src/legends/interfaces/update-legend-count.interface.ts
  src/tasks/tasks.service.ts
  src/users/dtos/update-user-nickname.dto.ts
  src/users/users-swagger/create-user-nickname.decorator.ts
  src/users/users-swagger/get-one-user.decorator.ts
  src/users/users-swagger/get-users.decorator.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: feature

#116 Feature/#115/nginx
  docker-compose.yml
  nginx.conf
  src/common/utils/logger/middleware/logger.middleware.ts
  src/main.ts
Labels: feature, setting

#117 Feature/#69/logout
  src/auth/auth.controller.ts
  src/auth/services/auth.service.ts
  src/auth/services/token.service.ts
  src/auth/swagger-decorators/google-logout-decorator.ts
  src/auth/swagger-decorators/google-unlink-decorator.ts
Labels: feature, modify

#118 Refactor/#87/user
  src/games/games.controller.ts
  src/games/rock-scissors-paper/dtos/get-date.dto.ts
  src/games/rock-scissors-paper/dtos/rock-scissors-paper.dto.ts
  src/games/rock-scissors-paper/rock-scissors-paper.repository.ts
  src/games/rock-scissors-paper/rock-scissors-paper.service.ts
  src/games/swagger-decorators/create-RSP-record.decorator.ts
  src/games/swagger-decorators/get-RSP-records.decorator.ts
Labels: modify

#119 refactor/#69: redis password 추가
  src/auth/redis/redis.module.ts
Labels: modify

#120 modify/#69
  src/auth/services/auth.service.ts
  src/users/users.repository.ts
Labels: feature, modify

#121 Refactor/#106/folder
  src/achievements/achievements.repository.ts
  src/alarms/alarms-swagger/get-alarms.decorator.ts
  src/alarms/alarms-swagger/update-alarm-status-to-read.decorator.ts
  src/alarms/alarms.controller.ts
  src/alarms/alarms.repository.ts
  src/app.module.ts
  src/characterLockers/characterLockers.repository.ts
  src/characters/characters.repository.ts
  src/comments/comments.module.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/swagger-decorators/comment-swagger/create-one-comment.decorator.ts
  src/comments/swagger-decorators/comment-swagger/update-comment.decorator.ts
  src/comments/swagger-decorators/reply-swagger/create-one-reply.decorator.ts
  src/comments/swagger-decorators/reply-swagger/get-replies.decorator.ts
  src/comments/swagger-decorators/reply-swagger/update-one-reply.decorator.ts
  src/common/common.module.ts
  src/common/common.service.ts
  src/games/games.module.ts
  src/games/rock-scissors-paper/rock-scissors-paper.repository.ts
  src/games/rock-scissors-paper/rock-scissors-paper.service.ts
  src/inventory/inventory.module.ts
  src/inventory/inventory.repository.ts
  src/inventory/inventory.service.ts
  src/items/items.repository.ts
  src/legends/legends.repository.ts
  src/likes/likes.module.ts
  src/likes/likes.service.ts
  src/neighbors/neighbors.repository.ts
  src/posts/dtos/get-posts.dto.ts
  src/posts/posts-swagger/create-one-post.decorator.ts
  src/posts/posts-swagger/get-one-post.decorator.ts
  src/posts/posts.repositroy.ts
  src/posts/posts.service.ts
  src/presents/dtos/present.dto.ts
  src/presents/dtos/presents-without-delete-response.dto.ts
  src/presents/presents-swagger/create-one-present.decorator.ts
  src/presents/presents.module.ts
  src/presents/presents.repository.ts
  src/presents/presents.service.ts
  src/sse/sse.controller.ts
  src/sse/swagger-decorators/connect-sse.decorator.ts
  src/user-achievements/user-achievements.module.ts
  src/user-achievements/user-achievements.repository.ts
  src/user-achievements/user-achievements.service.ts
  src/user-achievements/userAchievements-swagger/get-user-achievements.decorator.ts
  src/users/enum/domain.enum.ts
  src/users/users-swagger/create-user-nickname.decorator.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: delete, feature, refactor

#123 Modify/#122/userupdate
  src/auth/auth.controller.ts
  src/auth/services/auth.service.ts
  src/auth/swagger-decorators/updateProfile-decorator.ts
Labels: delete, modify

#125 Refactor/#106/folder
  src/auth/services/auth.service.ts
  src/comments/comments.repository.ts
  src/comments/constants/default-comments-select-options.constant.ts
  src/comments/constants/default-replies-select-options.constant.ts
  src/neighbors/constants/default-neighbors-select-options.constants.ts
  src/neighbors/constants/get-neighbors-select-options.constant.ts
  src/neighbors/neighbors.repository.ts
  src/posts/constants/default-post-select-options.constant.ts
  src/posts/posts.repositroy.ts
  src/posts/posts.service.ts
  src/presents/constants/default-presents-select-options.constant.ts
  src/presents/presents.repository.ts
  src/tasks/tasks.service.ts
  src/users/users.repository.ts
Labels: refactor

#127 Feature/#124/user
  src/tasks/tasks.service.ts
  src/users/users.repository.ts
Labels: feature

#128 Refactor/#87/user
  prisma/migrations/20240814070550_add_achievement_category/migration.sql
  prisma/schema.prisma
  src/user-achievements/dtos/get-user-achievements.dto.ts
  src/user-achievements/user-achievements.controller.ts
  src/user-achievements/user-achievements.repository.ts
  src/user-achievements/user-achievements.service.ts
  src/user-achievements/userAchievements-swagger/get-user-achievements.decorator.ts
Labels: feature

#130 refactor/#129/auth
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/services/auth.service.ts
  src/auth/services/google-auth.service.ts
  src/auth/services/kakao-auth.service.ts
  src/auth/services/naver-auth.service.ts
Labels: refactor

#131 Feature/#126/ban
  prisma/migrations/20240816040722_add_ban_table/migration.sql
  prisma/migrations/20240816050739_add_ban_autoincrement/migration.sql
  prisma/migrations/20240819060821_add_token_delete_cascade/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/redis/redis.service.ts
  src/auth/repositories/token.repository.ts
  src/auth/services/token.service.ts
  src/bans/bans-swagger/create-ban.decorator.ts
  src/bans/bans.controller.ts
  src/bans/bans.module.ts
  src/bans/bans.repository.ts
  src/bans/bans.service.ts
  src/bans/dtos/create-ban.dto.ts
  src/posts/posts.service.ts
  src/presents/presents.service.ts
  src/sse/swagger-decorators/connect-sse.decorator.ts
  src/user-achievements/dtos/get-user-achievements.dto.ts
  src/user-achievements/userAchievements-swagger/get-user-achievements.decorator.ts
  src/users/dtos/update-user-nickname.dto.ts
  src/users/users-swagger/create-user-nickname.decorator.ts
  src/users/users.repository.ts
Labels: feature

#134 Refactor/#106/folder
  src/achievements/dtos/get-achievements.dto.ts
  src/characters/dtos/get-characters.dto.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/games/rock-scissors-paper/rock-scissors-paper.service.ts
  src/inventory/dtos/get-user-items.dto.ts
  src/items/dtos/get-user-all-items.dto.ts
  src/likes/likes.service.ts
  src/neighbors/neighbors.service.ts
  src/posts/posts.service.ts
  src/presents/dtos/get-user-presents.dto.ts
  src/presents/presents.service.ts
  src/users/dtos/get-users-by-animal.dto.ts
Labels: bugfix, feature

#133 modify/#132/login
  src/auth/auth.module.ts
  src/auth/services/google-auth.service.ts
  src/auth/services/kakao-auth.service.ts
  src/auth/services/naver-auth.service.ts
  src/auth/swagger-decorators/google-login-decorator.ts
  src/auth/swagger-decorators/kakao-login-decorator.ts
  src/auth/swagger-decorators/naver-login-decorator.ts
  src/bans/bans.module.ts
  src/bans/bans.service.ts
Labels: modify

#136 Feature/#135/find like
  package-lock.json
  package.json
  prisma/schema.prisma
  src/common/dtos/sender-receiver-no.dto.ts
  src/likes/dtos/get-likes.dto.ts
  src/likes/likes-swagger/get-likes.decorator.ts
  src/likes/likes.controller.ts
  src/likes/likes.repository.ts
  src/likes/likes.service.ts
  src/presents/presents.controller.ts
  src/presents/presents.service.ts
Labels: feature

#137 comment, reply 하나 조회하는 로직 추가
  src/comments/comments.controller.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/swagger-decorators/comment-swagger/get-one-comment.dto.ts
  src/comments/swagger-decorators/reply-swagger/get-one-reply.decorator.ts
Labels: feature

#138 modify/#132
  src/auth/auth.controller.ts
  src/auth/services/auth.service.ts
  src/auth/services/google-auth.service.ts
  src/auth/services/kakao-auth.service.ts
  src/auth/services/naver-auth.service.ts
  src/auth/swagger-decorators/google-logout-decorator.ts
  src/auth/swagger-decorators/kakao-logout-decorator.ts
  src/auth/swagger-decorators/kakao-unlink-decorator.ts
  src/auth/swagger-decorators/logout-decorator.ts
  src/auth/swagger-decorators/naver-logout-decorator.ts
  src/auth/swagger-decorators/unlink-decorator.ts
Labels: modify, refactor

#141 docker image 경량화 작업
  .dockerignore
  dockerfile
  package.json
  src/prisma/prisma.service.spec.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
Labels: deploy, modify

#142 Refactor/#106/folder
  src/alarms/alarms.controller.ts
  src/alarms/alarms.service.ts
  src/bans/bans.service.ts
  src/comments/comments.controller.ts
  src/comments/comments.module.ts
  src/comments/comments.service.ts
  src/games/games.module.ts
  src/inventory/dtos/get-user-items.dto.ts
  src/items/items.repository.ts
  src/likes/likes.module.ts
  src/neighbors/neighbors.controller.ts
  src/neighbors/neighbors.module.ts
  src/neighbors/neighbors.service.ts
  src/posts/dtos/get-posts.dto.ts
  src/posts/posts.controller.ts
  src/posts/posts.module.ts
  src/posts/posts.service.ts
  src/presents/presents.controller.ts
  src/presents/presents.module.ts
  src/presents/presents.service.ts
  src/sse/sse.module.ts
  src/tasks/tasks.module.ts
  src/user-achievements/user-achievements.module.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: feature, modify, refactor
