Repository modern-agile-team/ModernWorld-back, pull requests merged in 2024-06, with the labels that each got.

#41 쪽지 관련 PR 입니다.
  src/app.module.ts
  src/main.ts
  src/posts/dto/create-post.dto.ts
  src/posts/dto/get-one-post.dto.ts
  src/posts/posts.controller.ts
  src/posts/posts.module.ts
  src/posts/posts.repositroy.ts
  src/posts/posts.service.ts
Labels: feature

#48 Feature/#42/like
  package-lock.json
  src/app.module.ts
  src/legends/legends.module.ts
  src/legends/legends.repository.ts
  src/likes/likes.controller.ts
  src/likes/likes.module.ts
  src/likes/likes.repository.ts
  src/likes/likes.service.ts
Labels: feature

#49 시드 파일 관련 PR 올립니다.
  .dockerignore
  prisma/seeding/chrarcterLocker.ts
  prisma/seeding/comment.ts
  prisma/seeding/inventory.ts
  prisma/seeding/item.ts
  prisma/seeding/like.ts
Labels: db, feature

#40 refactor/#22: swagger 설정
  package-lock.json
  src/comment/comment.controller.ts
  src/comment/dto/create-comment.dto.ts
  src/comment/dto/get-comment.dto.ts
  src/comment/swagger-decorators/create-comment-decorator.ts
  src/comment/swagger-decorators/delete-comments-decorator.ts
  src/comment/swagger-decorators/find-comments-decorator.ts
  src/comment/swagger-decorators/update-comment-decorator.ts
Labels: refactor

#57 winston을 이용한 로깅
  package-lock.json
  package.json
  src/app.module.ts
  src/common/common.module.ts
  src/common/middleware/logger.middleware.ts
  src/config/logger.config.ts
  src/main.ts
Labels: feature

#54 Feature/#51/sse
  src/app.module.ts
  src/sse/sse.controller.ts
  src/sse/sse.module.ts
  src/sse/sse.service.ts
  src/tasks/tasks.module.ts
  src/tasks/tasks.service.ts
  src/users/users.module.ts
Labels: feature
